// <auto-generated />
using System;
using CourseFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseFlow.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231023175807_youtubelink")]
    partial class youtubelink
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CourseFlow.Models.AuthorCourses", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuthorId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("AuthorCourses");
                });

            modelBuilder.Entity("CourseFlow.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad5d1e3e-9526-4079-9d37-cb219d73bab0"),
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = new Guid("60856cdc-8d7b-47e6-a1da-484c096df8a4"),
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            Id = new Guid("e17b5ece-a149-4fa9-a56f-fd55346bddba"),
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = new Guid("659d00ce-9984-4db8-9fda-9a985599cd80"),
                            Name = "Database Management"
                        },
                        new
                        {
                            Id = new Guid("24eaf1a2-f016-41fd-94e6-e350f3200183"),
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = new Guid("c7103a28-0ba5-490e-910d-bd0bb3d6eff5"),
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = new Guid("7482c1a2-99df-4b35-8465-b22f21694b4c"),
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = new Guid("e588549e-4be4-4e70-bea0-7a72419970a4"),
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = new Guid("f269bed0-dcd0-40ca-986e-b8b4595a2f02"),
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = new Guid("89b7d7c7-db02-4330-8ef0-0679f403dbb8"),
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = new Guid("e3bd7238-9a24-442f-8d06-932e84034f95"),
                            Name = "Frontend Development"
                        },
                        new
                        {
                            Id = new Guid("77d111fb-2f48-450f-a632-77783f5eb212"),
                            Name = "Backend Development"
                        },
                        new
                        {
                            Id = new Guid("65d75295-a07b-4af3-91f3-41f823d71d07"),
                            Name = "Full Stack Development"
                        },
                        new
                        {
                            Id = new Guid("419efda9-df80-4ecb-bfc7-a48fd20d4653"),
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = new Guid("3f4f8589-eb76-435d-8a6d-16aefeafad5b"),
                            Name = "Version Control"
                        },
                        new
                        {
                            Id = new Guid("5ba8a5c3-6263-43a2-a709-ded78127aac9"),
                            Name = "Agile Methodology"
                        },
                        new
                        {
                            Id = new Guid("3ce6188b-cc65-4e1f-9958-bbcbfac8f7a2"),
                            Name = "Software Testing"
                        },
                        new
                        {
                            Id = new Guid("dff23ce9-a1f6-4bd9-b36d-5f546d35b3de"),
                            Name = "Continuous Integration"
                        },
                        new
                        {
                            Id = new Guid("2a49fda8-75d1-44ad-8b9a-f5bd7f77efc2"),
                            Name = "API Development"
                        },
                        new
                        {
                            Id = new Guid("0a6813bb-b14f-40ef-90b6-8ffe45f26fb4"),
                            Name = "Microservices"
                        },
                        new
                        {
                            Id = new Guid("78629900-1724-4246-b1d2-f60952853ae7"),
                            Name = "Blockchain"
                        },
                        new
                        {
                            Id = new Guid("fd78bb25-d52d-4f56-bed3-1b3a953c41a0"),
                            Name = "IoT Development"
                        },
                        new
                        {
                            Id = new Guid("0e288f0d-0eea-4f0a-b8b8-3ff813a405da"),
                            Name = "Embedded Systems"
                        },
                        new
                        {
                            Id = new Guid("fa4c31a8-b150-4fe7-a9b9-4c9400bb17ee"),
                            Name = "Natural Language Processing"
                        },
                        new
                        {
                            Id = new Guid("ecbae5b9-67dd-4f2d-8f0a-bdd62c6234b5"),
                            Name = "Big Data"
                        },
                        new
                        {
                            Id = new Guid("aa292d24-7181-4689-82a6-d18f4ae1b09e"),
                            Name = "Virtual Reality"
                        },
                        new
                        {
                            Id = new Guid("272389a4-14f4-4cd9-9b0e-aa2719789dea"),
                            Name = "Augmented Reality"
                        },
                        new
                        {
                            Id = new Guid("c8f838a8-43c9-4ccd-a465-84152896b188"),
                            Name = "Quantum Computing"
                        },
                        new
                        {
                            Id = new Guid("d82f3ba5-8300-40d1-9b92-9628704fc1be"),
                            Name = "Functional Programming"
                        },
                        new
                        {
                            Id = new Guid("081d99b7-91de-44dd-acf1-72f30ffdce6c"),
                            Name = "Object-Oriented Programming"
                        },
                        new
                        {
                            Id = new Guid("9ba29c48-9c80-41c5-be03-db34bcc0d2f6"),
                            Name = "Low-Level Programming"
                        },
                        new
                        {
                            Id = new Guid("7d7d6d9a-842e-4df6-bc4b-badfee155070"),
                            Name = "High-Level Programming"
                        },
                        new
                        {
                            Id = new Guid("707c1df4-64fc-487b-adc9-80cb70582d7e"),
                            Name = "Concurrency"
                        },
                        new
                        {
                            Id = new Guid("807dc436-b362-439b-b779-dcdd6da43646"),
                            Name = "Parallel Programming"
                        },
                        new
                        {
                            Id = new Guid("6265412c-311e-400c-980a-110b21e59d03"),
                            Name = "Responsive Design"
                        },
                        new
                        {
                            Id = new Guid("f1bd8976-b0fc-46c9-8da7-4f3960b2ed2d"),
                            Name = "RESTful APIs"
                        },
                        new
                        {
                            Id = new Guid("d523e211-4664-4077-8f64-7ecccb8ba17f"),
                            Name = "GraphQL"
                        },
                        new
                        {
                            Id = new Guid("fa1ce48e-1eea-4c3c-b9fd-f75f102ca953"),
                            Name = "Secure Coding Practices"
                        },
                        new
                        {
                            Id = new Guid("12ef4cf6-b735-4fe5-aa62-016eb7878565"),
                            Name = "Code Optimization"
                        },
                        new
                        {
                            Id = new Guid("421dbef8-402b-4c0e-81e9-ea09694a16b6"),
                            Name = "Code Review"
                        },
                        new
                        {
                            Id = new Guid("811a1e13-0ddd-4cec-b5ab-d9a10896f979"),
                            Name = "Pair Programming"
                        },
                        new
                        {
                            Id = new Guid("16e3f3de-20c5-4b19-aa0e-c9a665b0e422"),
                            Name = "Scrum"
                        },
                        new
                        {
                            Id = new Guid("f758c3c5-ab28-42f2-a673-06b452d721c9"),
                            Name = "Kanban"
                        },
                        new
                        {
                            Id = new Guid("e05a2fe1-fe1f-452a-ac3d-e5d5c68dec46"),
                            Name = "Software Architecture"
                        },
                        new
                        {
                            Id = new Guid("09395321-1e6b-4d94-966b-82c74c479812"),
                            Name = "Design Patterns"
                        },
                        new
                        {
                            Id = new Guid("6e67d226-831d-42b1-bb6c-de8019d5db6b"),
                            Name = "Refactoring"
                        },
                        new
                        {
                            Id = new Guid("c16c7b98-276a-4797-aeb5-07da00b78a7c"),
                            Name = "Code Documentation"
                        },
                        new
                        {
                            Id = new Guid("1c04b3b5-6502-46f3-966d-efbb907dd95d"),
                            Name = "Legacy Code Maintenance"
                        },
                        new
                        {
                            Id = new Guid("e38e1587-ecdb-4352-82fa-cbe3f9e9af63"),
                            Name = "Code Quality"
                        },
                        new
                        {
                            Id = new Guid("799f7b99-089d-411d-a75c-e27434d931f1"),
                            Name = "Technical Debt"
                        },
                        new
                        {
                            Id = new Guid("d5784f58-85cd-44de-94b1-2602d3f12814"),
                            Name = "Software Development Lifecycle"
                        },
                        new
                        {
                            Id = new Guid("121d6aca-7210-4db5-8509-75d16bcac8d2"),
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = new Guid("87d07aa7-b9a5-4893-b32d-a35a91d9839f"),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("0b6ac92e-f658-410a-9a10-0555867b9316"),
                            Name = "C++"
                        },
                        new
                        {
                            Id = new Guid("bed78972-747d-423d-833f-d86ed466145c"),
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("31e23f19-95d4-4977-9236-204ea5b55e04"),
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("a6fa943f-2818-48d7-b759-658833ec6dbd"),
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("c61bb349-ad73-4a27-aa04-594bd5823971"),
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = new Guid("b0eb5b61-134a-4d3c-8b67-07383f200e69"),
                            Name = "Swift"
                        },
                        new
                        {
                            Id = new Guid("a2d5f3c9-a42c-4ca7-a125-0acaf89404b4"),
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = new Guid("8a2ce32b-982e-457f-8467-ece7439bf038"),
                            Name = "Go"
                        },
                        new
                        {
                            Id = new Guid("a74a2d1d-8a87-4b22-bc0a-fadf469e17f9"),
                            Name = "Rust"
                        },
                        new
                        {
                            Id = new Guid("54d76740-9449-4d78-9669-8448ed6f019a"),
                            Name = "PHP"
                        },
                        new
                        {
                            Id = new Guid("079822f0-c522-46e4-87f4-12f456b98727"),
                            Name = "Perl"
                        },
                        new
                        {
                            Id = new Guid("ec954d46-a14f-4a11-a6cf-7557ab810807"),
                            Name = "Scala"
                        },
                        new
                        {
                            Id = new Guid("e0e9d8b0-78d0-48c4-9a67-d9d8ccd88c87"),
                            Name = "Haskell"
                        },
                        new
                        {
                            Id = new Guid("970f3c9f-e444-498c-8a92-33e838c7f8dc"),
                            Name = "Lua"
                        },
                        new
                        {
                            Id = new Guid("3d3c6262-d487-472c-bfc3-282034ca8472"),
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("62173ac9-4a51-4e4e-9f92-f15ecd1e41a6"),
                            Name = "Dart"
                        },
                        new
                        {
                            Id = new Guid("067fdea0-956a-4569-8cf7-691604e8c47d"),
                            Name = "F#"
                        },
                        new
                        {
                            Id = new Guid("034b2a13-da9b-4799-bf8b-e9e6053dfd55"),
                            Name = "Groovy"
                        },
                        new
                        {
                            Id = new Guid("85bd1b30-074e-43e1-8003-fe4849c8e449"),
                            Name = "Objective-C"
                        },
                        new
                        {
                            Id = new Guid("7f51b372-e101-417a-a450-2248901c0137"),
                            Name = "R"
                        },
                        new
                        {
                            Id = new Guid("d9bc47bd-ce59-43b5-93f9-1cfbb330e112"),
                            Name = "Matlab"
                        },
                        new
                        {
                            Id = new Guid("a01945bd-ba94-4bdf-af65-0c8378443243"),
                            Name = "Julia"
                        },
                        new
                        {
                            Id = new Guid("a69fe2e8-28a5-45f6-acaf-4dbc025f00a4"),
                            Name = "COBOL"
                        },
                        new
                        {
                            Id = new Guid("14315e39-3108-4d5b-9dbb-fc98422b6472"),
                            Name = "Fortran"
                        },
                        new
                        {
                            Id = new Guid("4904f250-928b-41f8-be3a-1671d0e063cf"),
                            Name = "Assembly"
                        },
                        new
                        {
                            Id = new Guid("7e3ca18b-2413-41b4-b8e0-4126a636d294"),
                            Name = "PL/SQL"
                        },
                        new
                        {
                            Id = new Guid("ef7a5322-6f2d-4e99-b208-997972a98628"),
                            Name = "T-SQL"
                        },
                        new
                        {
                            Id = new Guid("95812431-8c46-41d4-9615-814d904849d6"),
                            Name = "VBScript"
                        },
                        new
                        {
                            Id = new Guid("23a3d2a9-d2ee-4edd-abfe-04f9ba336de7"),
                            Name = "Ada"
                        },
                        new
                        {
                            Id = new Guid("ed9bf13a-c237-45b9-acfe-7b3087d6a77a"),
                            Name = "Lisp"
                        },
                        new
                        {
                            Id = new Guid("b263abf7-ae7f-4589-986e-35f45d3f1561"),
                            Name = "Prolog"
                        },
                        new
                        {
                            Id = new Guid("1d2dfd2b-a159-4f31-9077-895921bcbdd8"),
                            Name = "Scheme"
                        },
                        new
                        {
                            Id = new Guid("12f4763c-5677-4562-9b07-4a78ad2854ce"),
                            Name = "Smalltalk"
                        },
                        new
                        {
                            Id = new Guid("27ce98b6-b1d1-4362-a666-6ee3f67b2c2f"),
                            Name = "Logo"
                        },
                        new
                        {
                            Id = new Guid("292e467e-af15-4754-adf9-18c37dfee4f0"),
                            Name = "Clojure"
                        },
                        new
                        {
                            Id = new Guid("ccf19e30-c2da-4802-a4dc-00734b0e7ede"),
                            Name = "Elixir"
                        },
                        new
                        {
                            Id = new Guid("554443b7-cd66-4e21-8130-0c288c576c89"),
                            Name = "Erlang"
                        },
                        new
                        {
                            Id = new Guid("cf554f9e-b912-4c0e-9c21-882cd62fc83a"),
                            Name = "VHDL"
                        },
                        new
                        {
                            Id = new Guid("9d1d55c6-9432-4d0c-b47e-d4dac637ca20"),
                            Name = "Verilog"
                        },
                        new
                        {
                            Id = new Guid("b2747df7-2570-402f-a345-a4ff6773e8d8"),
                            Name = "SQL"
                        },
                        new
                        {
                            Id = new Guid("945901c5-7157-47a0-880f-cb2209bfede4"),
                            Name = "HTML"
                        },
                        new
                        {
                            Id = new Guid("d0e2f804-15a5-43c2-9b69-c66a96c14d2f"),
                            Name = "CSS"
                        },
                        new
                        {
                            Id = new Guid("af23fffa-6f62-4945-b5a6-3ad87e057a88"),
                            Name = "XML"
                        },
                        new
                        {
                            Id = new Guid("817f23a9-026e-4770-86d0-dfb1447ffc78"),
                            Name = "JSON"
                        },
                        new
                        {
                            Id = new Guid("08baeb40-40b7-4f6f-97e2-6141e27e9a52"),
                            Name = "Bash"
                        },
                        new
                        {
                            Id = new Guid("988a57bc-a518-4134-9b1f-9cbe6c8fe596"),
                            Name = "PowerShell"
                        },
                        new
                        {
                            Id = new Guid("04cd8fbe-3f8d-463a-a30e-2c0528c7f949"),
                            Name = "Pascal"
                        },
                        new
                        {
                            Id = new Guid("a57a484d-7f70-4cef-8054-eeb63b18e036"),
                            Name = "Racket"
                        },
                        new
                        {
                            Id = new Guid("40e43878-e6e0-4878-a38e-0f05ad9a1bc8"),
                            Name = "Ada"
                        });
                });

            modelBuilder.Entity("CourseFlow.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CourseFlow.Models.CourseCategory", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CourseCategories");
                });

            modelBuilder.Entity("CourseFlow.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAssignedToCourse")
                        .HasColumnType("bit");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("CourseFlow.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CourseFlow.Models.UserTakesCourse", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("UserTakesCourses");
                });

            modelBuilder.Entity("CourseFlow.Models.AuthorCourses", b =>
                {
                    b.HasOne("CourseFlow.Models.User", "Author")
                        .WithMany("AuthorCourses")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("AuthorCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseFlow.Models.CourseCategory", b =>
                {
                    b.HasOne("CourseFlow.Models.Category", "Category")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseFlow.Models.Lesson", b =>
                {
                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseFlow.Models.UserTakesCourse", b =>
                {
                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("UserTakesCourse")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFlow.Models.User", "User")
                        .WithMany("UserTakesCourse")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseFlow.Models.Category", b =>
                {
                    b.Navigation("CourseCategories");
                });

            modelBuilder.Entity("CourseFlow.Models.Course", b =>
                {
                    b.Navigation("AuthorCourses");

                    b.Navigation("CourseCategories");

                    b.Navigation("Lessons");

                    b.Navigation("UserTakesCourse");
                });

            modelBuilder.Entity("CourseFlow.Models.User", b =>
                {
                    b.Navigation("AuthorCourses");

                    b.Navigation("UserTakesCourse");
                });
#pragma warning restore 612, 618
        }
    }
}
