// <auto-generated />
using System;
using CourseFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseFlow.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231023175612_LessonCourseOptional")]
    partial class LessonCourseOptional
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CourseFlow.Models.AuthorCourses", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuthorId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("AuthorCourses");
                });

            modelBuilder.Entity("CourseFlow.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a389707-c37f-4b1f-9051-db344baf4a2f"),
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = new Guid("a67d5e83-1849-47c6-a38d-c797762ed76d"),
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            Id = new Guid("862cd591-e705-49d5-be6b-47dcc9be8cae"),
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = new Guid("b5e72736-1168-4a73-8ffa-3e5614eadd31"),
                            Name = "Database Management"
                        },
                        new
                        {
                            Id = new Guid("dad86b90-20df-41dc-aa3f-61326847447a"),
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = new Guid("e5e5c263-76c2-474c-b25b-9ba09750e976"),
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = new Guid("48cbad00-371b-4ee3-b3fd-1ea72518be7d"),
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = new Guid("ef5a1215-511f-4876-a051-70f9c6dddfaf"),
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = new Guid("8d73ca83-bddb-4ae8-ab80-5a28fd6b42ff"),
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = new Guid("09f195f3-c48c-4695-8f2b-01ae7efd3dc2"),
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = new Guid("2503bd41-39fe-459c-b91e-af232cccece8"),
                            Name = "Frontend Development"
                        },
                        new
                        {
                            Id = new Guid("82a8ecc4-a932-4096-9d72-62e8f8d16a86"),
                            Name = "Backend Development"
                        },
                        new
                        {
                            Id = new Guid("7b094e0b-5341-4db6-8fa3-84e2b6fa9627"),
                            Name = "Full Stack Development"
                        },
                        new
                        {
                            Id = new Guid("618967f5-7257-4459-bb8e-8ce6b9e6a9e9"),
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = new Guid("ca63963e-b7d4-437d-9c69-d06a17271bcf"),
                            Name = "Version Control"
                        },
                        new
                        {
                            Id = new Guid("aabdded7-be49-43d1-abeb-2f8d92f8782a"),
                            Name = "Agile Methodology"
                        },
                        new
                        {
                            Id = new Guid("48fa7392-8e4a-4ce0-95a9-df1a9a2b5486"),
                            Name = "Software Testing"
                        },
                        new
                        {
                            Id = new Guid("835adc47-f805-49bb-9fea-b19decffa4ee"),
                            Name = "Continuous Integration"
                        },
                        new
                        {
                            Id = new Guid("f802308d-3548-41c7-a365-4acc30e31865"),
                            Name = "API Development"
                        },
                        new
                        {
                            Id = new Guid("68db5608-2c80-4235-a2ce-7f53965ddcc8"),
                            Name = "Microservices"
                        },
                        new
                        {
                            Id = new Guid("41173d9f-8f50-4c98-8756-d105d76aafac"),
                            Name = "Blockchain"
                        },
                        new
                        {
                            Id = new Guid("cb810114-eb9e-46c2-a23d-69108c22dbf6"),
                            Name = "IoT Development"
                        },
                        new
                        {
                            Id = new Guid("8da10f74-a634-46e6-b18e-82ba8c0a36cf"),
                            Name = "Embedded Systems"
                        },
                        new
                        {
                            Id = new Guid("718b4793-a1d1-45b6-8ae7-5e0089471fbb"),
                            Name = "Natural Language Processing"
                        },
                        new
                        {
                            Id = new Guid("6558b674-3e16-4058-bb37-26f78acc9dda"),
                            Name = "Big Data"
                        },
                        new
                        {
                            Id = new Guid("7d71b0b0-015e-44ec-a65e-f8a868fbf1b0"),
                            Name = "Virtual Reality"
                        },
                        new
                        {
                            Id = new Guid("e6bd1862-192f-47b5-b593-7a67027de998"),
                            Name = "Augmented Reality"
                        },
                        new
                        {
                            Id = new Guid("9acf9694-b1c5-46a1-b39f-84078c1fce8a"),
                            Name = "Quantum Computing"
                        },
                        new
                        {
                            Id = new Guid("31b22eca-387d-4c35-87dc-787abafd821b"),
                            Name = "Functional Programming"
                        },
                        new
                        {
                            Id = new Guid("e316d88c-4ac9-42d2-b9c3-46bb36b84e84"),
                            Name = "Object-Oriented Programming"
                        },
                        new
                        {
                            Id = new Guid("42e81703-57ca-4292-8ec5-90b4d63dde75"),
                            Name = "Low-Level Programming"
                        },
                        new
                        {
                            Id = new Guid("51316019-f700-449a-912d-26e67de93963"),
                            Name = "High-Level Programming"
                        },
                        new
                        {
                            Id = new Guid("ce099427-d7eb-45b5-b87e-43cfe20cce74"),
                            Name = "Concurrency"
                        },
                        new
                        {
                            Id = new Guid("4c54fc57-13e7-40d4-9748-0f85903ad503"),
                            Name = "Parallel Programming"
                        },
                        new
                        {
                            Id = new Guid("7a44fe3a-4ae2-47cc-8bac-e1eb8229088f"),
                            Name = "Responsive Design"
                        },
                        new
                        {
                            Id = new Guid("81fb2919-7b05-40f3-a18b-ffa55949d3c2"),
                            Name = "RESTful APIs"
                        },
                        new
                        {
                            Id = new Guid("a9a54e85-7b38-4c4d-b0e6-92c8787bb516"),
                            Name = "GraphQL"
                        },
                        new
                        {
                            Id = new Guid("9cabe68f-509c-4fbd-95b5-600a11f50ea3"),
                            Name = "Secure Coding Practices"
                        },
                        new
                        {
                            Id = new Guid("827af0f1-e5ca-4b5b-b208-3bb2935bd19e"),
                            Name = "Code Optimization"
                        },
                        new
                        {
                            Id = new Guid("39f59d71-23e4-49bb-b167-04f0c9b434dd"),
                            Name = "Code Review"
                        },
                        new
                        {
                            Id = new Guid("6b375bb2-1602-49cc-a79a-bc9d14a46e84"),
                            Name = "Pair Programming"
                        },
                        new
                        {
                            Id = new Guid("bf984ba0-cf88-482d-a7c1-c62d6163d5ca"),
                            Name = "Scrum"
                        },
                        new
                        {
                            Id = new Guid("d47fdec6-da0c-49d8-8ca1-990875f4c357"),
                            Name = "Kanban"
                        },
                        new
                        {
                            Id = new Guid("e1971a30-8c34-453e-a9bb-55fbcdf961b7"),
                            Name = "Software Architecture"
                        },
                        new
                        {
                            Id = new Guid("2744d859-3eaf-485e-81e3-8f00d02dbaa5"),
                            Name = "Design Patterns"
                        },
                        new
                        {
                            Id = new Guid("1e35c324-28b9-482b-9a64-914b180704d3"),
                            Name = "Refactoring"
                        },
                        new
                        {
                            Id = new Guid("c7368f45-48e7-45dd-99d4-9d6634c58441"),
                            Name = "Code Documentation"
                        },
                        new
                        {
                            Id = new Guid("73558f68-d354-43cd-b2bf-b4e96c547f5e"),
                            Name = "Legacy Code Maintenance"
                        },
                        new
                        {
                            Id = new Guid("e8277d31-fb27-4ff5-94b8-c018bc9e3938"),
                            Name = "Code Quality"
                        },
                        new
                        {
                            Id = new Guid("dd295385-4bd9-4e51-bd58-b9da026be491"),
                            Name = "Technical Debt"
                        },
                        new
                        {
                            Id = new Guid("67250fb8-f4b8-427b-8eb8-5b05799cf3dd"),
                            Name = "Software Development Lifecycle"
                        },
                        new
                        {
                            Id = new Guid("d4251572-c6bf-4af6-b5d4-4998af43bd44"),
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = new Guid("3b30ae5b-4341-40e8-a3b6-9d890155057b"),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("d706fec6-eb7a-4a12-bb68-b2867e40a9ba"),
                            Name = "C++"
                        },
                        new
                        {
                            Id = new Guid("02209f4a-52f5-4a8a-b69f-252fe7d0afc2"),
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("4854dd78-47be-414c-90f3-e1b55adc1a3f"),
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("19ab9711-69e2-4e13-9acf-ad87a28627ff"),
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("ffb54d7f-ae0c-4b3b-aabd-7505f1f5681d"),
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = new Guid("4b326a2a-d6d0-4169-97b9-c6c646883e56"),
                            Name = "Swift"
                        },
                        new
                        {
                            Id = new Guid("2f571a38-1509-4bb1-aa95-91de65dbec35"),
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = new Guid("7e3a75b2-6887-4278-bacd-82d921b44c80"),
                            Name = "Go"
                        },
                        new
                        {
                            Id = new Guid("dd8dd621-5cd9-4e77-bd4b-0f21ad247085"),
                            Name = "Rust"
                        },
                        new
                        {
                            Id = new Guid("1bc5d269-fc0e-4069-82ca-a4f7053de818"),
                            Name = "PHP"
                        },
                        new
                        {
                            Id = new Guid("05be7165-ccf1-4bb2-b99d-0f139f1fdcaf"),
                            Name = "Perl"
                        },
                        new
                        {
                            Id = new Guid("e5bc8f66-b9d9-4855-804a-3ea6bcb305b6"),
                            Name = "Scala"
                        },
                        new
                        {
                            Id = new Guid("9a654440-ba92-4e98-8c08-fb5a23a5984b"),
                            Name = "Haskell"
                        },
                        new
                        {
                            Id = new Guid("da7ee0f8-483c-4cc3-b2ad-140ecf30c84d"),
                            Name = "Lua"
                        },
                        new
                        {
                            Id = new Guid("d7b28ca4-86d7-42b0-879d-3250c10b3f81"),
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("a91a59a6-7026-4f48-8b6f-5b70029d10df"),
                            Name = "Dart"
                        },
                        new
                        {
                            Id = new Guid("83f29ea4-0b36-4d5c-a492-651a9c608bc0"),
                            Name = "F#"
                        },
                        new
                        {
                            Id = new Guid("39ca98d2-3737-40b4-9e40-322a349d046b"),
                            Name = "Groovy"
                        },
                        new
                        {
                            Id = new Guid("d40c2c2c-188d-4a67-881d-27e6fe3ac734"),
                            Name = "Objective-C"
                        },
                        new
                        {
                            Id = new Guid("397a0909-98d8-4564-89c6-1e6ed14e0c32"),
                            Name = "R"
                        },
                        new
                        {
                            Id = new Guid("6bd97c71-5faa-49a5-9608-c45d1d212c2e"),
                            Name = "Matlab"
                        },
                        new
                        {
                            Id = new Guid("540bb408-b100-41dc-9d01-3105b5404568"),
                            Name = "Julia"
                        },
                        new
                        {
                            Id = new Guid("a2340903-7134-40d9-a1c3-b1b41b64d0b4"),
                            Name = "COBOL"
                        },
                        new
                        {
                            Id = new Guid("73cbff9f-1352-41a8-ae19-b1ea12aca68d"),
                            Name = "Fortran"
                        },
                        new
                        {
                            Id = new Guid("3e066e4b-c07b-4f21-b3a2-75a3bb321feb"),
                            Name = "Assembly"
                        },
                        new
                        {
                            Id = new Guid("254e20d6-30ce-4b93-b852-926e0edfae24"),
                            Name = "PL/SQL"
                        },
                        new
                        {
                            Id = new Guid("4c9acd88-a41c-400f-82f4-caf32e1553e7"),
                            Name = "T-SQL"
                        },
                        new
                        {
                            Id = new Guid("7b4fa6c5-8605-4462-93b5-4cbc35b5662e"),
                            Name = "VBScript"
                        },
                        new
                        {
                            Id = new Guid("f37145d5-ff07-43cf-bfe0-569ab6f92847"),
                            Name = "Ada"
                        },
                        new
                        {
                            Id = new Guid("ec4fd0bf-9bcc-4a41-b556-2d639080fe75"),
                            Name = "Lisp"
                        },
                        new
                        {
                            Id = new Guid("5a8b4254-f3db-4d0a-a7fa-f56a460bd6da"),
                            Name = "Prolog"
                        },
                        new
                        {
                            Id = new Guid("6acd56e6-e543-4e9c-9f51-c73d521d568e"),
                            Name = "Scheme"
                        },
                        new
                        {
                            Id = new Guid("d5cc2f8c-91fd-48f0-bd1e-d8dc2be0d6cc"),
                            Name = "Smalltalk"
                        },
                        new
                        {
                            Id = new Guid("d6ff7a13-df7a-4cf2-b130-8d10de0116ba"),
                            Name = "Logo"
                        },
                        new
                        {
                            Id = new Guid("8bfa8296-9c4e-40b0-ba13-fad650038110"),
                            Name = "Clojure"
                        },
                        new
                        {
                            Id = new Guid("515c2ff7-8864-4eff-8a47-93f713185066"),
                            Name = "Elixir"
                        },
                        new
                        {
                            Id = new Guid("5dd40923-fcb0-4ff3-a4fc-cdbe9b487969"),
                            Name = "Erlang"
                        },
                        new
                        {
                            Id = new Guid("cf61de3d-aba5-4f34-a8f1-0f7849fd6263"),
                            Name = "VHDL"
                        },
                        new
                        {
                            Id = new Guid("93ccabca-3d78-4c27-bcac-f00f9da5454a"),
                            Name = "Verilog"
                        },
                        new
                        {
                            Id = new Guid("1007354e-d1f4-4c15-9e92-85a1f2f4b548"),
                            Name = "SQL"
                        },
                        new
                        {
                            Id = new Guid("6c2e727a-94a0-4586-b815-ae64e440490e"),
                            Name = "HTML"
                        },
                        new
                        {
                            Id = new Guid("82e44541-2374-42cd-bc7e-d329180377be"),
                            Name = "CSS"
                        },
                        new
                        {
                            Id = new Guid("928beb59-3c77-4c20-9e44-cfca965c5697"),
                            Name = "XML"
                        },
                        new
                        {
                            Id = new Guid("9d474497-6a65-41df-8fa3-ce3b54067154"),
                            Name = "JSON"
                        },
                        new
                        {
                            Id = new Guid("62b447ab-efd5-435d-896c-bd63cc361d73"),
                            Name = "Bash"
                        },
                        new
                        {
                            Id = new Guid("99e8cf9d-319f-49d0-a0a6-94eb2c2870b1"),
                            Name = "PowerShell"
                        },
                        new
                        {
                            Id = new Guid("b2fdd6e8-6cd5-48cf-b201-26dbc4709473"),
                            Name = "Pascal"
                        },
                        new
                        {
                            Id = new Guid("242d93de-a9c3-48a7-8e7b-099fb20c98a6"),
                            Name = "Racket"
                        },
                        new
                        {
                            Id = new Guid("e162360a-256b-4744-a8e5-988cc6cdc506"),
                            Name = "Ada"
                        });
                });

            modelBuilder.Entity("CourseFlow.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CourseFlow.Models.CourseCategory", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CourseCategories");
                });

            modelBuilder.Entity("CourseFlow.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAssignedToCourse")
                        .HasColumnType("bit");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("CourseFlow.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CourseFlow.Models.UserTakesCourse", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("UserTakesCourses");
                });

            modelBuilder.Entity("CourseFlow.Models.AuthorCourses", b =>
                {
                    b.HasOne("CourseFlow.Models.User", "Author")
                        .WithMany("AuthorCourses")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("AuthorCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseFlow.Models.CourseCategory", b =>
                {
                    b.HasOne("CourseFlow.Models.Category", "Category")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseFlow.Models.Lesson", b =>
                {
                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseFlow.Models.UserTakesCourse", b =>
                {
                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("UserTakesCourse")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFlow.Models.User", "User")
                        .WithMany("UserTakesCourse")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseFlow.Models.Category", b =>
                {
                    b.Navigation("CourseCategories");
                });

            modelBuilder.Entity("CourseFlow.Models.Course", b =>
                {
                    b.Navigation("AuthorCourses");

                    b.Navigation("CourseCategories");

                    b.Navigation("Lessons");

                    b.Navigation("UserTakesCourse");
                });

            modelBuilder.Entity("CourseFlow.Models.User", b =>
                {
                    b.Navigation("AuthorCourses");

                    b.Navigation("UserTakesCourse");
                });
#pragma warning restore 612, 618
        }
    }
}
