// <auto-generated />
using System;
using CourseFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseFlow.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231029124449_lessontracker")]
    partial class lessontracker
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CourseFlow.Models.AuthorCourses", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuthorId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("AuthorCourses");
                });

            modelBuilder.Entity("CourseFlow.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4f6ba63-6bb0-4463-b8a3-2fd8c4477e4e"),
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = new Guid("7d4b03e0-546e-4de4-a840-40ae6e504a82"),
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            Id = new Guid("aad6256d-de0f-4feb-b11a-5355ddca6f40"),
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = new Guid("feeb9197-5ee0-4818-81f7-3ae813cde922"),
                            Name = "Database Management"
                        },
                        new
                        {
                            Id = new Guid("38e4a675-dc3f-460e-a0aa-49154eb19fc1"),
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = new Guid("abe5b712-bd88-4737-be98-f88a25d2a354"),
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = new Guid("b59351b7-8f28-42ab-8b81-96cd0563cb70"),
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = new Guid("ad37fafa-b994-4b68-ac05-f7df16699e6b"),
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = new Guid("74387423-252a-47c6-a20c-1ddece2824ed"),
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = new Guid("5ff18e14-145c-476a-a6f9-d89fc5102e6a"),
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = new Guid("2f6dafaa-80b9-4655-9ee1-5eabdf611e82"),
                            Name = "Frontend Development"
                        },
                        new
                        {
                            Id = new Guid("b60b86d3-9d54-463d-8867-7537f9f33dea"),
                            Name = "Backend Development"
                        },
                        new
                        {
                            Id = new Guid("2aeb2588-c05c-42d2-9bc7-d996004793cd"),
                            Name = "Full Stack Development"
                        },
                        new
                        {
                            Id = new Guid("4d09ad81-f273-435b-b646-eb28e77786dd"),
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = new Guid("4ca543fb-1a3b-4d53-abe8-68b037125e4c"),
                            Name = "Version Control"
                        },
                        new
                        {
                            Id = new Guid("1012ce10-6bcc-4f57-b92b-4fe61f3bdaa9"),
                            Name = "Agile Methodology"
                        },
                        new
                        {
                            Id = new Guid("c6e7beb6-cf75-4d90-a156-cda685b7ac30"),
                            Name = "Software Testing"
                        },
                        new
                        {
                            Id = new Guid("a71083b8-43d9-4246-93d7-c94d938d805b"),
                            Name = "Continuous Integration"
                        },
                        new
                        {
                            Id = new Guid("62925b32-8d05-4c3a-85d5-e20bc09daf6d"),
                            Name = "API Development"
                        },
                        new
                        {
                            Id = new Guid("cbb5f3d9-697d-419f-a303-9344a68dc85f"),
                            Name = "Microservices"
                        },
                        new
                        {
                            Id = new Guid("6b8655c0-1f27-41c7-aff8-837f0ef6d2a5"),
                            Name = "Blockchain"
                        },
                        new
                        {
                            Id = new Guid("f0d71629-12e9-4bb9-9039-1dbead80db8e"),
                            Name = "IoT Development"
                        },
                        new
                        {
                            Id = new Guid("4c7c6ffc-18a6-4a8d-9926-51baf524113a"),
                            Name = "Embedded Systems"
                        },
                        new
                        {
                            Id = new Guid("30f647d8-4208-42c9-b0fa-7cf4001f6807"),
                            Name = "Natural Language Processing"
                        },
                        new
                        {
                            Id = new Guid("8c61922f-b9a7-4eff-ad2f-48a307a81bf6"),
                            Name = "Big Data"
                        },
                        new
                        {
                            Id = new Guid("bef792de-5460-4098-ba2f-6d404ab163d3"),
                            Name = "Virtual Reality"
                        },
                        new
                        {
                            Id = new Guid("ae1182fc-fe45-4d22-9514-06102b40abad"),
                            Name = "Augmented Reality"
                        },
                        new
                        {
                            Id = new Guid("deabe57e-0ce1-4a76-a632-695757718bed"),
                            Name = "Quantum Computing"
                        },
                        new
                        {
                            Id = new Guid("fa4174ed-be41-4a71-bdc2-a92dd5034a98"),
                            Name = "Functional Programming"
                        },
                        new
                        {
                            Id = new Guid("09984e51-1094-4e2c-bd76-6b42b4981af1"),
                            Name = "Object-Oriented Programming"
                        },
                        new
                        {
                            Id = new Guid("a001b9d8-a665-4502-8ce8-883d4860a3aa"),
                            Name = "Low-Level Programming"
                        },
                        new
                        {
                            Id = new Guid("2485ec1f-0028-4010-8300-e661d1e46b3a"),
                            Name = "High-Level Programming"
                        },
                        new
                        {
                            Id = new Guid("a1dbd8f0-79bf-4e46-882c-e19824f81ddf"),
                            Name = "Concurrency"
                        },
                        new
                        {
                            Id = new Guid("8e157997-c4d1-4d71-ac8f-b706e5256108"),
                            Name = "Parallel Programming"
                        },
                        new
                        {
                            Id = new Guid("effeb1b0-fa50-40f1-bf9c-0279e9bd0525"),
                            Name = "Responsive Design"
                        },
                        new
                        {
                            Id = new Guid("aa2cb5f6-5df8-452b-892e-6db191cd4500"),
                            Name = "RESTful APIs"
                        },
                        new
                        {
                            Id = new Guid("4a0f195c-1745-457b-89db-4864ae5b896a"),
                            Name = "GraphQL"
                        },
                        new
                        {
                            Id = new Guid("31e789aa-a50e-4c35-8283-668be007baf6"),
                            Name = "Secure Coding Practices"
                        },
                        new
                        {
                            Id = new Guid("a40aef3a-696d-4e80-a20b-f9c6ccad9424"),
                            Name = "Code Optimization"
                        },
                        new
                        {
                            Id = new Guid("a2e5bf07-7f8f-4c40-8f00-d37a6d132c9c"),
                            Name = "Code Review"
                        },
                        new
                        {
                            Id = new Guid("4ba771e7-7fa4-47d1-bd83-81a2d861bb9b"),
                            Name = "Pair Programming"
                        },
                        new
                        {
                            Id = new Guid("489452d4-4644-4306-a9d4-7ae8f311c202"),
                            Name = "Scrum"
                        },
                        new
                        {
                            Id = new Guid("79a1fd0b-74ef-4ec2-87b0-e8bedbe1117a"),
                            Name = "Kanban"
                        },
                        new
                        {
                            Id = new Guid("fdf7320b-4488-495b-bfa8-1fc38e479b3d"),
                            Name = "Software Architecture"
                        },
                        new
                        {
                            Id = new Guid("a7a500fb-62d9-4f84-9e4a-a42f378e414a"),
                            Name = "Design Patterns"
                        },
                        new
                        {
                            Id = new Guid("6d90acfa-9a1a-4222-a661-dff2e9955e64"),
                            Name = "Refactoring"
                        },
                        new
                        {
                            Id = new Guid("591de876-bd52-4566-a3c7-f5ca8582158a"),
                            Name = "Code Documentation"
                        },
                        new
                        {
                            Id = new Guid("e328c667-1a46-4477-9697-0cc2f8eb2628"),
                            Name = "Legacy Code Maintenance"
                        },
                        new
                        {
                            Id = new Guid("7c278e7b-8d71-4165-8443-9301972c7bba"),
                            Name = "Code Quality"
                        },
                        new
                        {
                            Id = new Guid("f0513494-d1d8-4cfc-82ec-0fa9f3e5fa15"),
                            Name = "Technical Debt"
                        },
                        new
                        {
                            Id = new Guid("6a4567da-05d6-4b6e-90e3-2f4da7c2532b"),
                            Name = "Software Development Lifecycle"
                        },
                        new
                        {
                            Id = new Guid("c1cb86f7-7169-494d-a594-008d227c9324"),
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = new Guid("1b0e22da-6bdc-477c-b42a-b645fc030c74"),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("0cd566f8-d086-4a4e-a34a-4cef655d01fa"),
                            Name = "C++"
                        },
                        new
                        {
                            Id = new Guid("60992186-31a4-444b-8754-5081ae67d6a1"),
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("ac02f25d-9228-432e-bbed-4ef355782f2c"),
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("8d069f4b-71f8-43aa-9438-a5c0df161f39"),
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("d5ee1686-6687-4e67-99d1-5ed9e3b6d79e"),
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = new Guid("674f639d-b6f7-4511-80d8-9ec100021f98"),
                            Name = "Swift"
                        },
                        new
                        {
                            Id = new Guid("09a3c9fc-2c41-4b69-9dc8-635ba01246b8"),
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = new Guid("c7b90863-c937-46ea-9b31-7e9a04381b32"),
                            Name = "Go"
                        },
                        new
                        {
                            Id = new Guid("388397e5-cdce-48ec-a592-4de5dd513748"),
                            Name = "Rust"
                        },
                        new
                        {
                            Id = new Guid("3a22df39-3729-4e23-8698-5daebb497ce7"),
                            Name = "PHP"
                        },
                        new
                        {
                            Id = new Guid("ce1edc70-544d-440a-a1df-31c859868725"),
                            Name = "Perl"
                        },
                        new
                        {
                            Id = new Guid("543c5fae-fdc6-4b73-9d38-956ea5537509"),
                            Name = "Scala"
                        },
                        new
                        {
                            Id = new Guid("2c43fe64-e761-4c28-b0f3-4482ee850198"),
                            Name = "Haskell"
                        },
                        new
                        {
                            Id = new Guid("ae639404-c79d-41a9-bc1b-3fa330db432c"),
                            Name = "Lua"
                        },
                        new
                        {
                            Id = new Guid("c5992f4b-450d-421d-8f95-87e9b7cfc35b"),
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("9ee411d1-75d9-427b-ac2d-80da7c8a52cc"),
                            Name = "Dart"
                        },
                        new
                        {
                            Id = new Guid("e466d173-0b99-4697-9d96-94f211cd3d82"),
                            Name = "F#"
                        },
                        new
                        {
                            Id = new Guid("b490d903-c98e-4b5e-9e1f-150e237aace4"),
                            Name = "Groovy"
                        },
                        new
                        {
                            Id = new Guid("161fe1f3-b8cc-469a-84f4-49be0b84420f"),
                            Name = "Objective-C"
                        },
                        new
                        {
                            Id = new Guid("6df2aab5-0ea6-443a-962b-ae5973e0cb5a"),
                            Name = "R"
                        },
                        new
                        {
                            Id = new Guid("aa5fd93c-f43c-4506-8747-572ee1f450f0"),
                            Name = "Matlab"
                        },
                        new
                        {
                            Id = new Guid("dc2c2150-7ad5-4b74-9a53-e843ca449192"),
                            Name = "Julia"
                        },
                        new
                        {
                            Id = new Guid("1c2e678b-6965-453b-a0ea-c2ffac572a70"),
                            Name = "COBOL"
                        },
                        new
                        {
                            Id = new Guid("248c5777-cce7-4315-9684-4a1c1f61d23d"),
                            Name = "Fortran"
                        },
                        new
                        {
                            Id = new Guid("037f0b11-6c9d-4fd6-a6e4-6801824ac0fc"),
                            Name = "Assembly"
                        },
                        new
                        {
                            Id = new Guid("baac9eae-0a38-4cb1-a6b7-ecc33e6a1d9a"),
                            Name = "PL/SQL"
                        },
                        new
                        {
                            Id = new Guid("2006f376-7e32-4520-99cf-1e8d2448c2f8"),
                            Name = "T-SQL"
                        },
                        new
                        {
                            Id = new Guid("4e9a306d-a9c2-4ba2-ad7d-74f71ac57041"),
                            Name = "VBScript"
                        },
                        new
                        {
                            Id = new Guid("4170af1f-1475-4d12-b2a5-45283152d2a2"),
                            Name = "Ada"
                        },
                        new
                        {
                            Id = new Guid("10e044f3-a227-416e-a638-4cacd4b373d2"),
                            Name = "Lisp"
                        },
                        new
                        {
                            Id = new Guid("cced8e54-ad98-41e6-b63d-d4a56a189512"),
                            Name = "Prolog"
                        },
                        new
                        {
                            Id = new Guid("028bb60e-4873-4bd8-a6c5-9cfdc9aba3ec"),
                            Name = "Scheme"
                        },
                        new
                        {
                            Id = new Guid("f2b65a67-acb9-449c-b07f-c6bbb59ebf5c"),
                            Name = "Smalltalk"
                        },
                        new
                        {
                            Id = new Guid("008abfe1-b139-4ae1-8112-8b5652657c2b"),
                            Name = "Logo"
                        },
                        new
                        {
                            Id = new Guid("2c7980ca-9430-4208-a2ac-1a0601521799"),
                            Name = "Clojure"
                        },
                        new
                        {
                            Id = new Guid("eefdfeb9-16cc-40a2-b1af-db23f96fede8"),
                            Name = "Elixir"
                        },
                        new
                        {
                            Id = new Guid("fc4df367-02ac-42d7-aafb-86cab397ef91"),
                            Name = "Erlang"
                        },
                        new
                        {
                            Id = new Guid("f5f6b6a5-8682-41f7-9c3c-84bf20818b01"),
                            Name = "VHDL"
                        },
                        new
                        {
                            Id = new Guid("517a1e1e-388e-449a-b305-2e19a8dfd019"),
                            Name = "Verilog"
                        },
                        new
                        {
                            Id = new Guid("d0764f73-60d6-4c9a-957e-4ac30d4d185a"),
                            Name = "SQL"
                        },
                        new
                        {
                            Id = new Guid("23a07438-38e4-4e3c-8fdc-5058c1224a75"),
                            Name = "HTML"
                        },
                        new
                        {
                            Id = new Guid("4fb6ea88-bb84-4fe9-95c1-26fd56d68b4f"),
                            Name = "CSS"
                        },
                        new
                        {
                            Id = new Guid("8195b93d-b9ec-4af4-aa64-a63b702d67bd"),
                            Name = "XML"
                        },
                        new
                        {
                            Id = new Guid("b6a73a18-0742-4b3e-9b90-0830d867a9f7"),
                            Name = "JSON"
                        },
                        new
                        {
                            Id = new Guid("79c7d7a3-9a42-4168-828f-afa9fd204793"),
                            Name = "Bash"
                        },
                        new
                        {
                            Id = new Guid("f4fdeb67-f13a-4ac1-b129-79f1aea301f1"),
                            Name = "PowerShell"
                        },
                        new
                        {
                            Id = new Guid("3ad986fb-a287-405e-aed7-f8fd8fe5ca97"),
                            Name = "Pascal"
                        },
                        new
                        {
                            Id = new Guid("a7bcc85d-36bc-42e0-954f-88d9bdf21e1d"),
                            Name = "Racket"
                        },
                        new
                        {
                            Id = new Guid("4b2b3a3f-b0c3-48b6-bd97-c7caa762de66"),
                            Name = "Ada"
                        });
                });

            modelBuilder.Entity("CourseFlow.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8857cea7-4421-46e2-9deb-1f08a749297b"),
                            Author = "",
                            DateCreated = new DateTime(2023, 10, 29, 13, 44, 48, 824, DateTimeKind.Local).AddTicks(9295),
                            Description = "This is a course for unassigned lessons",
                            IsPublic = false,
                            Price = 100000,
                            Thumbnail = "https://img-c.udemycdn.com/course/750x422/473160_d929_3.jpg",
                            Title = "Admin"
                        });
                });

            modelBuilder.Entity("CourseFlow.Models.CourseCategory", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CourseCategories");
                });

            modelBuilder.Entity("CourseFlow.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("CourseFlow.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CourseFlow.Models.UserTakesCourse", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("UserTakesCourses");
                });

            modelBuilder.Entity("CourseFlow.Models.AuthorCourses", b =>
                {
                    b.HasOne("CourseFlow.Models.User", "Author")
                        .WithMany("AuthorCourses")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("AuthorCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseFlow.Models.CourseCategory", b =>
                {
                    b.HasOne("CourseFlow.Models.Category", "Category")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseFlow.Models.Lesson", b =>
                {
                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseFlow.Models.UserTakesCourse", b =>
                {
                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("UserTakesCourse")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFlow.Models.User", "User")
                        .WithMany("UserTakesCourse")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseFlow.Models.Category", b =>
                {
                    b.Navigation("CourseCategories");
                });

            modelBuilder.Entity("CourseFlow.Models.Course", b =>
                {
                    b.Navigation("AuthorCourses");

                    b.Navigation("CourseCategories");

                    b.Navigation("Lessons");

                    b.Navigation("UserTakesCourse");
                });

            modelBuilder.Entity("CourseFlow.Models.User", b =>
                {
                    b.Navigation("AuthorCourses");

                    b.Navigation("UserTakesCourse");
                });
#pragma warning restore 612, 618
        }
    }
}
