// <auto-generated />
using System;
using CourseFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseFlow.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231023174813_LessonToCourseToTrue")]
    partial class LessonToCourseToTrue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CourseFlow.Models.AuthorCourses", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuthorId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("AuthorCourses");
                });

            modelBuilder.Entity("CourseFlow.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e6fcac7-5609-42ac-9989-9f9be4f8259d"),
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = new Guid("3914a0fe-9879-4d54-88ef-a95de5c09b2a"),
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            Id = new Guid("83598441-6494-4b63-aa63-9fd55fecd102"),
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = new Guid("fd8cda2d-e971-438e-8fb9-b9016ab3200f"),
                            Name = "Database Management"
                        },
                        new
                        {
                            Id = new Guid("64f4ab44-1f50-4d1b-9adf-28768355a988"),
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = new Guid("33d63ebd-1b2d-4d32-a43d-597dbbea0f39"),
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = new Guid("64310c06-3684-43a3-b1c4-60df03519cd9"),
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = new Guid("1fb536c3-f43a-469b-beaa-e8e6a47d7531"),
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = new Guid("89b9a191-dfe8-4912-af5c-1e8b954bbacd"),
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = new Guid("5287f0d5-68c1-4d2a-b778-25ec881e0413"),
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = new Guid("27a4690b-2e2e-4b6d-93d9-67d7df000f58"),
                            Name = "Frontend Development"
                        },
                        new
                        {
                            Id = new Guid("6e85f216-c947-4f13-9d9a-3eb698b06186"),
                            Name = "Backend Development"
                        },
                        new
                        {
                            Id = new Guid("f3692e5e-c2a4-4afe-ba6d-8357f0a55870"),
                            Name = "Full Stack Development"
                        },
                        new
                        {
                            Id = new Guid("47520141-5f6b-45e2-9706-853e2edd6bb1"),
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = new Guid("6a5f34ce-8129-4556-ab87-6adaf2f6e011"),
                            Name = "Version Control"
                        },
                        new
                        {
                            Id = new Guid("a07d2f1e-0c6c-4b95-bd57-5d388d55b443"),
                            Name = "Agile Methodology"
                        },
                        new
                        {
                            Id = new Guid("f7a06ea6-2d99-457f-ab9b-a596c590a4c2"),
                            Name = "Software Testing"
                        },
                        new
                        {
                            Id = new Guid("03d16d3f-fcc5-426c-8c90-fca94d758802"),
                            Name = "Continuous Integration"
                        },
                        new
                        {
                            Id = new Guid("7b6def07-ac98-45a8-b2f1-fe5e2dac584f"),
                            Name = "API Development"
                        },
                        new
                        {
                            Id = new Guid("d224d2a1-b877-422d-a7e2-fe9f187f9329"),
                            Name = "Microservices"
                        },
                        new
                        {
                            Id = new Guid("6eae3951-f0df-4eac-b7cf-d918c7d7e5b3"),
                            Name = "Blockchain"
                        },
                        new
                        {
                            Id = new Guid("1513803a-d677-4e78-8ab1-902abdc2bc36"),
                            Name = "IoT Development"
                        },
                        new
                        {
                            Id = new Guid("7af30b50-371a-4b50-bbba-2b1f6af9c366"),
                            Name = "Embedded Systems"
                        },
                        new
                        {
                            Id = new Guid("1cdd9fb9-35b3-4807-89c9-693de58eac08"),
                            Name = "Natural Language Processing"
                        },
                        new
                        {
                            Id = new Guid("fa4330f1-c84a-4b13-838f-af220522ca68"),
                            Name = "Big Data"
                        },
                        new
                        {
                            Id = new Guid("f361664b-077b-40b6-a7ea-c45e3f37db3c"),
                            Name = "Virtual Reality"
                        },
                        new
                        {
                            Id = new Guid("ece8f626-93d1-4a6b-a536-907db30fdc59"),
                            Name = "Augmented Reality"
                        },
                        new
                        {
                            Id = new Guid("0be3ad30-8756-4f77-8719-4f0c2675c9fc"),
                            Name = "Quantum Computing"
                        },
                        new
                        {
                            Id = new Guid("c36f438d-a9a1-4cfd-8b4f-4a12560fe226"),
                            Name = "Functional Programming"
                        },
                        new
                        {
                            Id = new Guid("24cbcd31-dcb2-4d5a-b0db-d62751c74bdf"),
                            Name = "Object-Oriented Programming"
                        },
                        new
                        {
                            Id = new Guid("ad213095-0edb-4d38-8806-dd9e977036f1"),
                            Name = "Low-Level Programming"
                        },
                        new
                        {
                            Id = new Guid("14d21c3e-8c08-49d1-85d9-879c97932a5d"),
                            Name = "High-Level Programming"
                        },
                        new
                        {
                            Id = new Guid("f94bec17-83be-46ef-87ec-4dfa0bd62e69"),
                            Name = "Concurrency"
                        },
                        new
                        {
                            Id = new Guid("73e7da3f-2f60-4d27-9de4-93981634060a"),
                            Name = "Parallel Programming"
                        },
                        new
                        {
                            Id = new Guid("1e065ad5-b706-4f1c-8c85-ec4915772dc6"),
                            Name = "Responsive Design"
                        },
                        new
                        {
                            Id = new Guid("2a2985c0-99b5-473b-982d-290c817b70bc"),
                            Name = "RESTful APIs"
                        },
                        new
                        {
                            Id = new Guid("635f2101-e202-4985-b942-042f8115ae6a"),
                            Name = "GraphQL"
                        },
                        new
                        {
                            Id = new Guid("a480bf32-d35a-43d5-8ba8-1b27e9ba8d68"),
                            Name = "Secure Coding Practices"
                        },
                        new
                        {
                            Id = new Guid("d2047e1e-f1e6-40ba-8b69-8aec31511b5c"),
                            Name = "Code Optimization"
                        },
                        new
                        {
                            Id = new Guid("71713297-9759-4860-84c8-6f2c07d3a0c4"),
                            Name = "Code Review"
                        },
                        new
                        {
                            Id = new Guid("81322fc8-8da8-4dfe-8710-22a580884939"),
                            Name = "Pair Programming"
                        },
                        new
                        {
                            Id = new Guid("d91b4371-5c84-426e-8ff5-e719d9328b89"),
                            Name = "Scrum"
                        },
                        new
                        {
                            Id = new Guid("1c3e3c78-e843-453c-90b4-6cb9384749ba"),
                            Name = "Kanban"
                        },
                        new
                        {
                            Id = new Guid("58e95215-4cfe-4bd8-afd9-d35059382037"),
                            Name = "Software Architecture"
                        },
                        new
                        {
                            Id = new Guid("e27ccb1c-0ed7-4880-986d-52430e8efb4a"),
                            Name = "Design Patterns"
                        },
                        new
                        {
                            Id = new Guid("f3707c25-0e1d-42cb-8989-5afa817cfb1c"),
                            Name = "Refactoring"
                        },
                        new
                        {
                            Id = new Guid("21add2d6-6bb2-4ed5-9805-58a0188cc62b"),
                            Name = "Code Documentation"
                        },
                        new
                        {
                            Id = new Guid("95e81204-ea84-4647-b35f-397fa91bb0a6"),
                            Name = "Legacy Code Maintenance"
                        },
                        new
                        {
                            Id = new Guid("61d101d0-ae4f-4563-9650-33dab3b1a075"),
                            Name = "Code Quality"
                        },
                        new
                        {
                            Id = new Guid("243aed24-d76b-44f0-8a6a-c77761c8987d"),
                            Name = "Technical Debt"
                        },
                        new
                        {
                            Id = new Guid("b6957db1-1da1-4112-a728-fc1a1b59e2f2"),
                            Name = "Software Development Lifecycle"
                        },
                        new
                        {
                            Id = new Guid("0fe492ae-8eda-4bc4-aecb-7b5ecec9d7c4"),
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = new Guid("be2870d3-1623-400a-95ca-d4ee6686ae49"),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("b7513584-8ca5-45af-b114-124baec92a4a"),
                            Name = "C++"
                        },
                        new
                        {
                            Id = new Guid("9cd5c967-17d1-4d45-b7f8-f9fef1d52ce8"),
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("0fd68151-05a1-406f-ba51-e1c7da36c3b8"),
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("5ef8410e-93b5-41f8-8168-991b4610f6c4"),
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("8ef2f4b9-79cf-47dc-b7a4-c9b8292efe8b"),
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = new Guid("ede64d64-2388-488a-8674-4304fc7d3e12"),
                            Name = "Swift"
                        },
                        new
                        {
                            Id = new Guid("cb528368-52fd-48a2-b6c0-61daf0b4ed45"),
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = new Guid("42c21b9d-0583-46c1-b3a3-9ee7764b24ea"),
                            Name = "Go"
                        },
                        new
                        {
                            Id = new Guid("5950bb4e-29ac-4a54-880b-b51b69da5861"),
                            Name = "Rust"
                        },
                        new
                        {
                            Id = new Guid("1caac64c-07b9-4de8-9786-5f87b6ba3564"),
                            Name = "PHP"
                        },
                        new
                        {
                            Id = new Guid("4e77023e-96d1-4fa5-a189-cc274d7d08ee"),
                            Name = "Perl"
                        },
                        new
                        {
                            Id = new Guid("c1617eea-20bc-4e7e-bcad-58f8fc915c1a"),
                            Name = "Scala"
                        },
                        new
                        {
                            Id = new Guid("6d061777-070a-4768-a957-e529046a8da3"),
                            Name = "Haskell"
                        },
                        new
                        {
                            Id = new Guid("522532d8-bdae-4111-b100-79b0a05c1510"),
                            Name = "Lua"
                        },
                        new
                        {
                            Id = new Guid("aafb7217-befe-4f9f-b492-23ddd337fde7"),
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("f3b0a60e-de67-4b80-a301-86410a098c80"),
                            Name = "Dart"
                        },
                        new
                        {
                            Id = new Guid("4f28cabf-ceb4-4f17-9f0f-e0aa33048180"),
                            Name = "F#"
                        },
                        new
                        {
                            Id = new Guid("8397ba88-3b66-4f17-a3c1-4a17a34fb818"),
                            Name = "Groovy"
                        },
                        new
                        {
                            Id = new Guid("16a7c62d-4b5c-4386-8fc8-0c2f38cb55fe"),
                            Name = "Objective-C"
                        },
                        new
                        {
                            Id = new Guid("81dd3438-17b2-4cc9-af3e-8f6c66e7de45"),
                            Name = "R"
                        },
                        new
                        {
                            Id = new Guid("05273464-a720-4d6d-972c-537bb0bab6ab"),
                            Name = "Matlab"
                        },
                        new
                        {
                            Id = new Guid("0c0ccd7e-bfc3-43df-808c-5c1b0a5c3f59"),
                            Name = "Julia"
                        },
                        new
                        {
                            Id = new Guid("3c844cca-ec26-4c2c-a955-e791c16c49f3"),
                            Name = "COBOL"
                        },
                        new
                        {
                            Id = new Guid("c78d16f1-8fb4-4596-b6c7-76b47f4de2da"),
                            Name = "Fortran"
                        },
                        new
                        {
                            Id = new Guid("424ac841-9fbe-4525-a195-f78e2d3fbedf"),
                            Name = "Assembly"
                        },
                        new
                        {
                            Id = new Guid("79bccb1d-babe-40d1-82cb-7127af8a0974"),
                            Name = "PL/SQL"
                        },
                        new
                        {
                            Id = new Guid("da02d0a8-3e0f-4dda-98f2-92842d9973e4"),
                            Name = "T-SQL"
                        },
                        new
                        {
                            Id = new Guid("d683270a-5f42-4f57-ab3f-42d58b81724c"),
                            Name = "VBScript"
                        },
                        new
                        {
                            Id = new Guid("c284ca11-5e48-4092-ba6b-b90e8fc91f9e"),
                            Name = "Ada"
                        },
                        new
                        {
                            Id = new Guid("10cecf55-95ad-4f4c-bf80-47d171d245f7"),
                            Name = "Lisp"
                        },
                        new
                        {
                            Id = new Guid("37d2c962-09bd-4dc4-b641-bc8cc0d5c85f"),
                            Name = "Prolog"
                        },
                        new
                        {
                            Id = new Guid("69a1d394-53e7-4c94-8e7f-75cbdb476766"),
                            Name = "Scheme"
                        },
                        new
                        {
                            Id = new Guid("5345d9ad-37b6-472e-82ea-5dcb26e06d38"),
                            Name = "Smalltalk"
                        },
                        new
                        {
                            Id = new Guid("91df7125-007c-4da8-a5dd-cfef73b4fa3b"),
                            Name = "Logo"
                        },
                        new
                        {
                            Id = new Guid("cc9b3008-cc8b-49c5-a2a4-dafbe8911dcd"),
                            Name = "Clojure"
                        },
                        new
                        {
                            Id = new Guid("372bd3d4-1663-42e3-9bd1-1273e3c809fb"),
                            Name = "Elixir"
                        },
                        new
                        {
                            Id = new Guid("2348b50b-61fc-4dd3-8cda-92f1b80f1ad3"),
                            Name = "Erlang"
                        },
                        new
                        {
                            Id = new Guid("2517b9d7-92e4-4674-8492-4a2290cafb11"),
                            Name = "VHDL"
                        },
                        new
                        {
                            Id = new Guid("5d0da045-97f7-42ad-99c7-12b506cefdc1"),
                            Name = "Verilog"
                        },
                        new
                        {
                            Id = new Guid("cafa63d6-3735-4dbc-920c-155132ceca6e"),
                            Name = "SQL"
                        },
                        new
                        {
                            Id = new Guid("8cac88a0-82f8-4539-a1ca-9995d183443c"),
                            Name = "HTML"
                        },
                        new
                        {
                            Id = new Guid("bad4ed8e-187d-49fb-bcc0-97a8e57ab0ac"),
                            Name = "CSS"
                        },
                        new
                        {
                            Id = new Guid("14221e08-e5aa-4dea-acb8-038fdf4e2126"),
                            Name = "XML"
                        },
                        new
                        {
                            Id = new Guid("c72437d5-0ded-469f-a5ab-73ba55699efc"),
                            Name = "JSON"
                        },
                        new
                        {
                            Id = new Guid("69538aac-234e-4fc8-8d71-4c5c88c2f0cb"),
                            Name = "Bash"
                        },
                        new
                        {
                            Id = new Guid("71f47b9b-3bb4-410b-b708-4b59218cb225"),
                            Name = "PowerShell"
                        },
                        new
                        {
                            Id = new Guid("748b67dc-a572-4c49-bbf9-a92a30bcf0d9"),
                            Name = "Pascal"
                        },
                        new
                        {
                            Id = new Guid("58ae2aa9-da75-49db-9e9c-c15cfc24921a"),
                            Name = "Racket"
                        },
                        new
                        {
                            Id = new Guid("b0704c9d-e35c-4a77-a18b-900dc2e50d40"),
                            Name = "Ada"
                        });
                });

            modelBuilder.Entity("CourseFlow.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CourseFlow.Models.CourseCategory", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CourseCategories");
                });

            modelBuilder.Entity("CourseFlow.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAssignedToCourse")
                        .HasColumnType("bit");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("CourseFlow.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CourseFlow.Models.UserTakesCourse", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("UserTakesCourses");
                });

            modelBuilder.Entity("CourseFlow.Models.AuthorCourses", b =>
                {
                    b.HasOne("CourseFlow.Models.User", "Author")
                        .WithMany("AuthorCourses")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("AuthorCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseFlow.Models.CourseCategory", b =>
                {
                    b.HasOne("CourseFlow.Models.Category", "Category")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseFlow.Models.Lesson", b =>
                {
                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseFlow.Models.UserTakesCourse", b =>
                {
                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("UserTakesCourse")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFlow.Models.User", "User")
                        .WithMany("UserTakesCourse")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseFlow.Models.Category", b =>
                {
                    b.Navigation("CourseCategories");
                });

            modelBuilder.Entity("CourseFlow.Models.Course", b =>
                {
                    b.Navigation("AuthorCourses");

                    b.Navigation("CourseCategories");

                    b.Navigation("Lessons");

                    b.Navigation("UserTakesCourse");
                });

            modelBuilder.Entity("CourseFlow.Models.User", b =>
                {
                    b.Navigation("AuthorCourses");

                    b.Navigation("UserTakesCourse");
                });
#pragma warning restore 612, 618
        }
    }
}
