// <auto-generated />
using System;
using CourseFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseFlow.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CourseFlow.Models.AuthorCourses", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuthorId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("AuthorCourses");
                });

            modelBuilder.Entity("CourseFlow.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db382238-cff0-4945-a383-7ecc2d1185b3"),
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = new Guid("8553923b-0cda-4ea7-9e63-1457dd626874"),
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            Id = new Guid("68590d17-96bb-4651-8467-47b09612f671"),
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = new Guid("ce065892-5640-483b-957b-f94a845f40b0"),
                            Name = "Database Management"
                        },
                        new
                        {
                            Id = new Guid("c6483daf-4a13-476f-a724-01b9653c8c36"),
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = new Guid("7e14d93d-7a7d-4137-b845-dc64dafe7a3e"),
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = new Guid("c9c04394-2477-4230-89ec-b26ccd1bc765"),
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = new Guid("f4b813ed-0eb5-49dd-ac46-e28540111764"),
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = new Guid("2fd7fb71-532e-4e1c-a617-81bc6edb578b"),
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = new Guid("ffa801e2-87d2-479e-97cb-accca7d594ca"),
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = new Guid("b3c56616-9248-4409-98b7-efa619402de7"),
                            Name = "Frontend Development"
                        },
                        new
                        {
                            Id = new Guid("4998b627-8cd2-4984-a029-4317bb8588af"),
                            Name = "Backend Development"
                        },
                        new
                        {
                            Id = new Guid("5e119e79-f13b-4f1f-88a5-f0f4485cfd14"),
                            Name = "Full Stack Development"
                        },
                        new
                        {
                            Id = new Guid("dcd1982b-73c9-4404-a179-f8a91bc880eb"),
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = new Guid("4a05aec2-c6f0-4a49-8f1a-84602884ca38"),
                            Name = "Version Control"
                        },
                        new
                        {
                            Id = new Guid("33399a7e-e4dc-46c0-9a88-a2e2d55b197a"),
                            Name = "Agile Methodology"
                        },
                        new
                        {
                            Id = new Guid("2d9051c0-c0b4-4803-9b91-bf3663bf2372"),
                            Name = "Software Testing"
                        },
                        new
                        {
                            Id = new Guid("715e80ba-0f10-462e-a692-5e7bb727c9e4"),
                            Name = "Continuous Integration"
                        },
                        new
                        {
                            Id = new Guid("1b6b4c7b-21c8-4882-97a5-b119b16fa1fc"),
                            Name = "API Development"
                        },
                        new
                        {
                            Id = new Guid("e839aaa8-5219-4fc5-8526-2cce5a41b36f"),
                            Name = "Microservices"
                        },
                        new
                        {
                            Id = new Guid("41400d85-c654-4356-b92c-9669624a9433"),
                            Name = "Blockchain"
                        },
                        new
                        {
                            Id = new Guid("4df0a9ae-6a02-4d9e-9784-6894de5b0fa3"),
                            Name = "IoT Development"
                        },
                        new
                        {
                            Id = new Guid("3efd0807-d218-4216-9337-ab17331832a7"),
                            Name = "Embedded Systems"
                        },
                        new
                        {
                            Id = new Guid("2aef8c0c-f1cf-4eb4-8293-74cc5c01d70a"),
                            Name = "Natural Language Processing"
                        },
                        new
                        {
                            Id = new Guid("3cc39ff2-09fb-4db2-9283-a4d859cbf3a9"),
                            Name = "Big Data"
                        },
                        new
                        {
                            Id = new Guid("51dcf428-c559-413e-ab11-02f27598b500"),
                            Name = "Virtual Reality"
                        },
                        new
                        {
                            Id = new Guid("d12b625f-5d47-4a17-8368-4567ea4c0bd1"),
                            Name = "Augmented Reality"
                        },
                        new
                        {
                            Id = new Guid("2aea7464-1d89-4942-9646-b0a31e893d5b"),
                            Name = "Quantum Computing"
                        },
                        new
                        {
                            Id = new Guid("4e815cab-4f0b-422c-af1e-f9828e839c10"),
                            Name = "Functional Programming"
                        },
                        new
                        {
                            Id = new Guid("ef649654-7e4f-475d-8cfa-67466caf394d"),
                            Name = "Object-Oriented Programming"
                        },
                        new
                        {
                            Id = new Guid("501aebae-2a40-4633-a5fe-e5440609ffac"),
                            Name = "Low-Level Programming"
                        },
                        new
                        {
                            Id = new Guid("67c23709-a386-426f-b7fe-d0b7a2531ae4"),
                            Name = "High-Level Programming"
                        },
                        new
                        {
                            Id = new Guid("d6e9fde1-e671-448a-aab6-043b88b1051f"),
                            Name = "Concurrency"
                        },
                        new
                        {
                            Id = new Guid("9424e7e8-46fd-4e0b-9e36-689524b965f0"),
                            Name = "Parallel Programming"
                        },
                        new
                        {
                            Id = new Guid("46a24453-82ac-42c1-9e4c-178e6723715a"),
                            Name = "Responsive Design"
                        },
                        new
                        {
                            Id = new Guid("ab27b14d-b234-43e5-aed5-cfe36a126b12"),
                            Name = "RESTful APIs"
                        },
                        new
                        {
                            Id = new Guid("ec2dba26-6bce-4c25-9571-54eaffdfa962"),
                            Name = "GraphQL"
                        },
                        new
                        {
                            Id = new Guid("cf90021d-870f-4e5d-ba92-c8e4d3d6e637"),
                            Name = "Secure Coding Practices"
                        },
                        new
                        {
                            Id = new Guid("c0ae1bf9-18e3-4e03-bccf-239b462acb2c"),
                            Name = "Code Optimization"
                        },
                        new
                        {
                            Id = new Guid("df60b52f-9033-410c-a2a9-107e6350d8d2"),
                            Name = "Code Review"
                        },
                        new
                        {
                            Id = new Guid("8c334614-0029-4d68-ab43-9faa87d8e22f"),
                            Name = "Pair Programming"
                        },
                        new
                        {
                            Id = new Guid("8f662b44-1b82-4be6-8b63-0707abc5f3a1"),
                            Name = "Scrum"
                        },
                        new
                        {
                            Id = new Guid("713d7035-1b8a-4c30-9d18-ce5ce6ddba7d"),
                            Name = "Kanban"
                        },
                        new
                        {
                            Id = new Guid("1731ddca-d190-4fb0-9af0-10d49bbc3d27"),
                            Name = "Software Architecture"
                        },
                        new
                        {
                            Id = new Guid("59c340e3-ff57-4fa1-a784-097471cb3f92"),
                            Name = "Design Patterns"
                        },
                        new
                        {
                            Id = new Guid("a34a8a87-d27c-4a9e-ac18-18571dc1154f"),
                            Name = "Refactoring"
                        },
                        new
                        {
                            Id = new Guid("037a28d7-3b74-4ce4-9d4d-f774212cb30f"),
                            Name = "Code Documentation"
                        },
                        new
                        {
                            Id = new Guid("2400172d-69f8-45b1-aaa5-649ea322de71"),
                            Name = "Legacy Code Maintenance"
                        },
                        new
                        {
                            Id = new Guid("e4887193-1068-49e7-b0cc-b3e119c6fd5e"),
                            Name = "Code Quality"
                        },
                        new
                        {
                            Id = new Guid("12493564-dbae-4636-a4c1-e746e722faa1"),
                            Name = "Technical Debt"
                        },
                        new
                        {
                            Id = new Guid("821dbdb4-52b9-40ef-a25a-eedfc6970bd6"),
                            Name = "Software Development Lifecycle"
                        },
                        new
                        {
                            Id = new Guid("e60b9995-440b-408c-830e-fcabaabd26b5"),
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = new Guid("7330c965-303c-42cb-b2de-988213bbb75e"),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("bc9e3aac-d9c9-4edb-b184-db0da90f5d3f"),
                            Name = "C++"
                        },
                        new
                        {
                            Id = new Guid("6b8fa3d0-d077-44d2-8117-c329ca4b7fdd"),
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("54546eb8-4233-43e4-a581-285e2690e7e2"),
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("aef7587f-f97c-4e03-a910-90b9fddba5f0"),
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("e82c01ec-bb90-4878-b3cd-d3f5d9282e4c"),
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = new Guid("c19e74be-dff5-4a09-b536-81185659d5f5"),
                            Name = "Swift"
                        },
                        new
                        {
                            Id = new Guid("c0970dd3-d39d-4c2e-ad05-27e6c005c8d8"),
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = new Guid("b6d76165-212d-41c9-8eda-d8bc1ad3f552"),
                            Name = "Go"
                        },
                        new
                        {
                            Id = new Guid("24339a38-54fa-4951-a5a9-d0670d87af32"),
                            Name = "Rust"
                        },
                        new
                        {
                            Id = new Guid("f5e22745-9600-4cf7-9737-4837a70e1b40"),
                            Name = "PHP"
                        },
                        new
                        {
                            Id = new Guid("452a8987-af35-49b3-ae39-da879366c48f"),
                            Name = "Perl"
                        },
                        new
                        {
                            Id = new Guid("c32d5a86-01ff-43bc-814d-b499245b7cf5"),
                            Name = "Scala"
                        },
                        new
                        {
                            Id = new Guid("28571322-2dc2-4213-9552-71b527b4ddf3"),
                            Name = "Haskell"
                        },
                        new
                        {
                            Id = new Guid("ee1aa5b7-3f92-4ea7-96af-cf3c638387bc"),
                            Name = "Lua"
                        },
                        new
                        {
                            Id = new Guid("ed98057d-85e9-4055-a36d-e0e8084552fa"),
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("43d34224-b9f0-4e4a-bb57-8fd561b8583c"),
                            Name = "Dart"
                        },
                        new
                        {
                            Id = new Guid("018a9552-31b6-4b1e-b696-c47d1e793549"),
                            Name = "F#"
                        },
                        new
                        {
                            Id = new Guid("d9021177-1163-4f4c-86ae-a6dfbca7161e"),
                            Name = "Groovy"
                        },
                        new
                        {
                            Id = new Guid("b0642461-cb20-4f69-bf78-2deb83a2d56a"),
                            Name = "Objective-C"
                        },
                        new
                        {
                            Id = new Guid("13691608-8c5f-4057-8f74-9a5a5e24ca24"),
                            Name = "R"
                        },
                        new
                        {
                            Id = new Guid("44e162ee-71f0-437b-901d-7f9f336af830"),
                            Name = "Matlab"
                        },
                        new
                        {
                            Id = new Guid("dc3f6be6-34b2-4d68-9925-36b3fdf41298"),
                            Name = "Julia"
                        },
                        new
                        {
                            Id = new Guid("6bc3d656-74d8-449d-a42c-c74bc28f08e9"),
                            Name = "COBOL"
                        },
                        new
                        {
                            Id = new Guid("9c713eb7-3628-4f02-be41-63b09333116c"),
                            Name = "Fortran"
                        },
                        new
                        {
                            Id = new Guid("9ca892cc-f6f3-4197-b2e1-947b3845cc42"),
                            Name = "Assembly"
                        },
                        new
                        {
                            Id = new Guid("b482af6c-57c5-4975-af46-c95f8be6d067"),
                            Name = "PL/SQL"
                        },
                        new
                        {
                            Id = new Guid("ecc60842-1e26-4216-a731-9c3acd36fa1d"),
                            Name = "T-SQL"
                        },
                        new
                        {
                            Id = new Guid("5791ea33-d561-4445-9d43-d7a709c3ebed"),
                            Name = "VBScript"
                        },
                        new
                        {
                            Id = new Guid("2d0e4892-ab73-4677-ac0c-f8743d8e1204"),
                            Name = "Ada"
                        },
                        new
                        {
                            Id = new Guid("3ea4bffe-bece-4ab5-9dda-7ff1a733cbba"),
                            Name = "Lisp"
                        },
                        new
                        {
                            Id = new Guid("320687b0-afd3-4936-9475-97efd874628b"),
                            Name = "Prolog"
                        },
                        new
                        {
                            Id = new Guid("ac1a19ae-00af-4ad6-b81f-de21b47300f2"),
                            Name = "Scheme"
                        },
                        new
                        {
                            Id = new Guid("e0e386b5-fd78-42fe-be73-20c32fb020b7"),
                            Name = "Smalltalk"
                        },
                        new
                        {
                            Id = new Guid("5c6e8936-0542-45f7-9eb3-2194793c5d3e"),
                            Name = "Logo"
                        },
                        new
                        {
                            Id = new Guid("43ad45ff-0b7a-4580-bfc5-386dc091d0ea"),
                            Name = "Clojure"
                        },
                        new
                        {
                            Id = new Guid("45823c9a-abae-411b-8181-7e669b72bda1"),
                            Name = "Elixir"
                        },
                        new
                        {
                            Id = new Guid("7ea6d9d0-4136-47da-b90d-bc060b2b0413"),
                            Name = "Erlang"
                        },
                        new
                        {
                            Id = new Guid("35fefad7-1a0a-421d-9171-79a36598de6e"),
                            Name = "VHDL"
                        },
                        new
                        {
                            Id = new Guid("6dac0161-80b3-4c92-93da-b3d3c67e1092"),
                            Name = "Verilog"
                        },
                        new
                        {
                            Id = new Guid("24c175b8-e5ed-4781-bd9f-cf692b0ef19c"),
                            Name = "SQL"
                        },
                        new
                        {
                            Id = new Guid("939cca06-bccf-44b4-86c4-4a785a54ef02"),
                            Name = "HTML"
                        },
                        new
                        {
                            Id = new Guid("34e3e7b2-2c62-45bb-b70a-690e6c68ec93"),
                            Name = "CSS"
                        },
                        new
                        {
                            Id = new Guid("c3840178-6fc9-4c02-997d-2a074b6fb7a5"),
                            Name = "XML"
                        },
                        new
                        {
                            Id = new Guid("7785d965-f420-48c3-a1b3-a47c438e833b"),
                            Name = "JSON"
                        },
                        new
                        {
                            Id = new Guid("e0d6bf0c-346c-4bf4-8d93-ea25152ff99a"),
                            Name = "Bash"
                        },
                        new
                        {
                            Id = new Guid("917896d6-4c77-4c17-bbfa-4fa396ec0088"),
                            Name = "PowerShell"
                        },
                        new
                        {
                            Id = new Guid("db8342b3-63a2-4018-a0b8-cdc1955646d6"),
                            Name = "Pascal"
                        },
                        new
                        {
                            Id = new Guid("43ae9ea7-88d9-4fc6-a13c-23a4e1560f0a"),
                            Name = "Racket"
                        },
                        new
                        {
                            Id = new Guid("289d8f22-b692-4c85-976e-31ed74ab2dd2"),
                            Name = "Ada"
                        });
                });

            modelBuilder.Entity("CourseFlow.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CourseFlow.Models.CourseCategory", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CourseCategories");
                });

            modelBuilder.Entity("CourseFlow.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("CourseFlow.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CourseFlow.Models.UserTakesCourse", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("UserTakesCourse");
                });

            modelBuilder.Entity("CourseFlow.Models.AuthorCourses", b =>
                {
                    b.HasOne("CourseFlow.Models.User", "Author")
                        .WithMany("AuthorCourses")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("AuthorCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseFlow.Models.CourseCategory", b =>
                {
                    b.HasOne("CourseFlow.Models.Category", "Category")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseFlow.Models.Lesson", b =>
                {
                    b.HasOne("CourseFlow.Models.Course", null)
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId");
                });

            modelBuilder.Entity("CourseFlow.Models.UserTakesCourse", b =>
                {
                    b.HasOne("CourseFlow.Models.Course", "Course")
                        .WithMany("UserTakesCourse")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseFlow.Models.User", "User")
                        .WithMany("UserTakesCourse")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseFlow.Models.Category", b =>
                {
                    b.Navigation("CourseCategories");
                });

            modelBuilder.Entity("CourseFlow.Models.Course", b =>
                {
                    b.Navigation("AuthorCourses");

                    b.Navigation("CourseCategories");

                    b.Navigation("Lessons");

                    b.Navigation("UserTakesCourse");
                });

            modelBuilder.Entity("CourseFlow.Models.User", b =>
                {
                    b.Navigation("AuthorCourses");

                    b.Navigation("UserTakesCourse");
                });
#pragma warning restore 612, 618
        }
    }
}
